CNKAF-843: Fix remove broker validation check (#1965)
* CNKAF-843: Fix remove broker validation check

Validate check for broker existence checks against a collection that
only has alive broker. So it fails with validation error:

> org.apache.kafka.common.errors.InvalidRequestException: Unknown broker
id specified: List(1)

Fix it to check against collection that contains all broker ids,
including dead ones. This change updates that part of validation and
adds few unit tests to check for all invalid broker id validation case
as well as removal of dead broker.